# Generated by Django 2.1.4 on 2019-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiles',
            name='image1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image5',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image6',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
