# Generated by Django 2.1.4 on 2019-07-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0003_auto_20190724_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiles',
            options={'verbose_name_plural': 'Tiles'},
        ),
    ]
