# Generated by Django 2.1.4 on 2019-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0008_about_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
