# Generated by Django 2.1.4 on 2019-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0009_auto_20190731_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video1',
            field=models.TextField(default='Video not available'),
        ),
    ]
