# Generated by Django 2.1.4 on 2019-08-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0010_auto_20190731_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video2',
            field=models.TextField(default='Video not available'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video3',
            field=models.TextField(default='Video not available'),
        ),
    ]
