# Generated by Django 2.1.4 on 2019-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0011_auto_20190801_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_para',
            field=models.TextField(default='Fill it out'),
        ),
    ]
