# Generated by Django 2.1.4 on 2019-08-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0012_auto_20190801_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.TextField(default='facebook.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.TextField(default='youtube.com'),
        ),
    ]
