# Generated by Django 2.1.4 on 2019-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0013_auto_20190801_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='my_map',
            field=models.TextField(default='map not available'),
        ),
    ]
