# Generated by Django 2.1.4 on 2019-08-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantra_site', '0014_about_my_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiles',
            name='image1_heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiles',
            name='image1_para',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image2_heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiles',
            name='image2_para',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image3_heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiles',
            name='image3_para',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image4_heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiles',
            name='image4_para',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image5_heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiles',
            name='image5_para',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tiles',
            name='image6_heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiles',
            name='image6_para',
            field=models.TextField(default=''),
        ),
    ]
